### PR TITLE
refactor folder structure and add swagger and dashboard to ci/cd

### PR DESCRIPTION
**Pull request by ironmanwaring**

### CODE REVIEW

**Comment by ironmanwaring** [comment]
@paulSambolin I messed up and did a big bang change, right after i asked everyone not to do that.  please review first thing in the morning - i had to change the jenkins server config to match, so environments probably won't be working correctly until this is merged

**Comment by paulSambolin** [comment]
Will do

**Comment by paulSambolin** [comment]
On fire last night.  Did you test jenkins and codepipeline with version number 1? I had previously ran into issues with the version numbers . Other than that it looks good

**Comment by ironmanwaring** [comment]
Jenkins is working with that config, yeah.  Right now the API is failing to
build but it looks like a whoso config issue with the project itself.

**Comment by paulSambolin** [comment]
Yes the version number needs to  be updated in jenkins as well. I can do it when I get to office

**Comment by ironmanwaring** [comment]
Last comment should have been webpack config, not whoso, lol

**Comment by paulSambolin** [comment]
Oh boy that will be more fun to figure out

**Pull request merged**
