### PR TITLE
added openssl as alternative to letsencrypt

### PR DESCRIPTION
**Pull request by paulSambolin**

### CODE REVIEW

**Comment by paulSambolin** [comment]
Don't merge until it can be tested with letsencrypt (currently exceeded limit on requests)

**Comment by paulSambolin** [comment]
resolve #148

**Comment by ironmanwaring** [comment]
once tested lgtm

**Comment by ironmanwaring** [comment]
lgtm

**Comment by paulSambolin** [comment]
resolves #149
resolves #148

**Comment by ironmanwaring** [comment]
is anything blocking this from a merge?

**Comment by paulSambolin** [comment]
Testing both options right now, but I don't foresee any issues with it

**Pull request merged**
